#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.8

pipelines:
  default:
    - parallel:
      - step:
          name: Test
          caches:
            - pip
          script:
            - if [ -f src/anchorscad/requirements.txt ]; then pip install -r src/anchorscad/requirements.txt; fi
            - git clone https://github.com/owebeeone/pythonopenscad.git
            - pip install pytest
            - PYTHONPATH="$PWD/src:$PWD/pythonopenscad/src:$PYTHONPATH" pytest -v src/tests/* --junitxml=test-reports/report.xml
      - step:
          name: Lint code
          script:
            # Enforce style consistency across Python projects https://flake8.pycqa.org/en/latest/manpage.html
            - pip install flake8
            - git clone https://github.com/owebeeone/pythonopenscad.git
            - PYTHONPATH="$PWD/src:$PWD/pythonopenscad/src:$PYTHONPATH" flake8 . --extend-exclude=dist,build --show-source --statistics
